### ISSUE TITLE
Minesweeper 

### ISSUE THREAD

**Issue by demiler** [OzerovaDaria/Minesweeper#2]
Задачи:

**Comment by demiler** [comment]
У нас три основные задачи: ui, логика и тестирование/деплоймент. Для ui мы можем использовать встроенный модуль `curses` или библиотеку вокруг него [blessed](https://pypi.org/project/blessed/). Логика относительно простая: игрок нажал на поле, где есть мина - конец, игра нажал на пустое поле - открыть пустые ячейки вокруг, игрок открыл последнюю пустую ячейку и пометил ровно N/N бомб - победа. Тестирование и деплой, это надо смотреть по тем штукам, что Курячий скидывал, на первое время - просто ^C ^V.

Задачи UI:
- [x] Нарисовать главное меню (пункты: игра, статистика, настройки, выход)
- - [x] Игра - перекидывает пользователя в меню настройки игры
- - [x] Статистика - показывает игроку статистику за игры
- - [x] Настройки - перебрасывает в меню настроек
- - [x] Выход - закрывает игру и возвращает терминал в прежние настройки
- [x] Нарисовать меню игры:
- - [x] Начать - перекидывает игрока в интерфейс игрового поля
- - [x] Сложность - указывает количество/соотношение бомб на поле
- - [x] Размер поля - указывает размер игрового поля
- [x] Нарисовать меню настроек:
- - [x] Язык - замена локализации программы
- - [ ] Игрок - замена имени игрока
- - [x] Цвета - включает/выключает цвета
- - [ ] Звуки - включает/выключает звуки
- - [x] Курсор - меняет символ курсора
- - [ ] Клавиши - меняет управление
- [x] Нарисовать игровое поле:
- - [x] Нарисовать рамку нужного размера
- - [x] Над рамкой поместить информацию о текущей игре
- - - [x] Сверху: статус игры (пауза/в процессе), прогресс %, отмечено бомб, открыто клеток
- - [x] Закрасив задний фон цветом отрисовать внутри рамки поле
- - [x] Отрисовать курсор
- - [x] Отрисовать количество бомб вокруг клетки соответствующим образом
- - [x] Отрисовать помеченные бомбы (разными цветами - возможно/точно)
- - [x] Отрисовать надписи: Пауза, Конец игры, Победа
- - [x] Отрисовать "взрыв" при открытии клетки с бомбой

Задачи бэкенда:
- [x] Обновлять конфиг при обновлении настроек
- [x] Получать данные о настройках игры в меню игры
- [x] Открывать все пустые клетки по координатам
- [x] Давать информацию о кол-ве бомб вокруг/в клетке по координате

Задачи тестирования и деплоймента:
- [x] Автоматизировать переключение между меню (или написать способ их обойти)
- [x] Проверять текущую информацию об игре

**Comment by demiler** [comment]
Напишите, кто какую задачу хочет взят (можем меняться во время написания проекта). Я готов взяться на ui, но не принципиально

**Comment by Andrey2001** [comment]
Я могу взять логику и, так как её мало, ещё часть UI

**Comment by demiler** [comment]
думаю, что возможно стоит действительно разделяться не просто ui/логика/тестирование, а как-то собрать подзадачи этих задач и выполнять их. Например:
- [ ] Меню игры и запоминание параметров
- [ ] Меню настроек и модификация конфиг файла
- [ ] Отрисовка поля и открытие пустых клеток вокруг конкретной точки
- [ ] Отрисовка курсора на поле, его передвижение, маркировка ячеек
- [ ] Сбор статистики об игре и отрисовка статус баров
- [ ] Главное меню с переходом в подменю, восстановление терминала при выходе
- [ ] Отрисовка надписей на полем
- [ ] Сохранение статистики игры и отрисовка таблицы статистики

**Comment by dzrlva** [comment]
я готова взять дизайн меню и отрисовать поле

**Comment by Andrey2001** [comment]
я возьму оба пункта со статистикой и буду проверять и подправлять все файлы под pydocstyle.

**Comment by demiler** [comment]
Макеты для создания GUI дизайна

Макет дизайна игры:
![game_proto](https://user-images.githubusercontent.com/36563353/173515683-345cdd5b-5bed-438a-9b4a-a65a4dadcead.png)

Макет главного меню:
![main_menu_proto](https://user-images.githubusercontent.com/36563353/173515687-849a2725-3261-4be6-b12f-18b8cfad9091.png)

Макет параметров новой игры:
![new_game_menu_proto](https://user-images.githubusercontent.com/36563353/173515689-05f357b8-d77d-41ca-ab73-2dd4105c51ac.png)

Макет настроек приложения
![settings_menu_proto](https://user-images.githubusercontent.com/36563353/173515692-2a2a0b9a-1c25-4926-aeb8-0087272b5514.png)
